language: node_js
node_js:
  - 'iojs-v3.0.0'
services:
  - mongodb
before_script:
  - export PATH="$PATH:$(npm bin)"
script:
  - npm update
  - npm test
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
