# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "mongodb" do |mongodb|
    mongodb.vm.box = "ubuntu/trusty64"
    mongodb.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh" # SSH
    mongodb.vm.network "forwarded_port", guest: 27017, host: 27017 # MongoDB
    mongodb.vm.provision "shell", inline: "echo \"export LC_ALL=en_US.UTF-8\" >> ~/.profile"
    mongodb.vm.provision "shell", path: "provision/mongodb.sh"
  end

end
